CREATE TABLE users (
    user_id VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    user_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE board (
    post_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR2(50) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    view_count NUMBER DEFAULT 0 NOT NULL,
    content CLOB NOT NULL,
    PRIMARY KEY (post_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE board_comment (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id NUMBER NOT NULL,
    user_id VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    content VARCHAR2(255) NOT NULL,
    deleted_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (deleted_flag IN ('Y', 'N')),
    parent_comment_id NUMBER NULL,
    comment_level NUMBER DEFAULT 0 NOT NULL,
    PRIMARY KEY (comment_id),
    FOREIGN KEY (post_id) REFERENCES board (post_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (parent_comment_id) REFERENCES board_comment (comment_id)
);

CREATE TABLE board_comment_like (
    comment_id NUMBER NOT NULL,
    user_id VARCHAR2(50) NOT NULL,
    like_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (like_flag IN ('Y', 'N')),
    PRIMARY KEY (comment_id, user_id),
    FOREIGN KEY (comment_id) REFERENCES board_comment (comment_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE board_like (
    post_id NUMBER NOT NULL,
    user_id VARCHAR2(50) NOT NULL,
    like_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (like_flag IN ('Y', 'N')),
    PRIMARY KEY (post_id, user_id),
    FOREIGN KEY (post_id) REFERENCES board (post_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);
